var Froogaloop=function(){function a(b){return new a.fn.init(b)}function b(a,b,c){if(!c.contentWindow.postMessage)return!1;var d=c.getAttribute("src").split("?")[0],a=JSON.stringify({method:a,value:b});"//"===d.substr(0,2)&&(d=window.location.protocol+d);c.contentWindow.postMessage(a,d)}function c(a){var b,c;try{b=JSON.parse(a.data),c=b.event||b.method}catch(d){}"ready"==c&&!f&&(f=!0);if(a.origin!=g)return!1;var a=b.value,h=b.data,i=""===i?null:b.player_id;b=i?e[i][c]:e[c];c=[];if(!b)return!1;void 0!==a&&c.push(a);h&&c.push(h);i&&c.push(i);return 0<c.length?b.apply(null,c):b.call()}function d(a,b,c){c?(e[c]||(e[c]={}),e[c][a]=b):e[a]=b}var e={},f=!1,g="";a.fn=a.prototype={element:null,init:function(a){"string"===typeof a&&(a=document.getElementById(a));this.element=a;a=this.element.getAttribute("src");"//"===a.substr(0,2)&&(a=window.location.protocol+a);for(var a=a.split("/"),b="",c=0,d=a.length;c<d;c++){if(3>c)b+=a[c];else break;2>c&&(b+="/")}g=b;return this},api:function(a,c){if(!this.element||!a)return!1;var e=this.element,f=""!==e.id?e.id:null,g=!c||!c.constructor||!c.call||!c.apply?c:null,h=c&&c.constructor&&c.call&&c.apply?c:null;h&&d(a,h,f);b(a,g,e);return this},addEvent:function(a,c){if(!this.element)return!1;var e=this.element,g=""!==e.id?e.id:null;d(a,c,g);"ready"!=a?b("addEventListener",a,e):"ready"==a&&f&&c.call(null,g);return this},removeEvent:function(a){if(!this.element)return!1;var c=this.element,d;a:{if((d=""!==c.id?c.id:null)&&e[d]){if(!e[d][a]){d=!1;break a}e[d][a]=null}else{if(!e[a]){d=!1;break a}e[a]=null}d=!0}"ready"!=a&&d&&b("removeEventListener",a,c)}};a.fn.init.prototype=a.fn;window.addEventListener?window.addEventListener("message",c,!1):window.attachEvent("onmessage",c);return window.Froogaloop=window.$f=a}();(function(){var a=false;var b=false;var c=false;var d=false;var e=false;var f=false;var g;var h=function(){clearTimeout(g);$("body").addClass("disable-hover");var h=$(window).scrollTop();var i=$(window).height();var j=h-i;var k,l;if(h>0){a=true;b=true;$("#content").addClass("active");$("#landing-header > div > h1").addClass("active");$("#landing-header-preorder").addClass("active");$("#landing-header-logo").removeClass("active")}if(h>80){$("#nav").addClass("scrolled")}else{$("#nav").removeClass("scrolled")}if(h>160){$("#nav").addClass("active")}else{$("#nav").removeClass("active")}$("#landing-tech > div > img.toggle").removeClass("active");if(j>=-250&&j<-182){$("#landing-tech-emv-2").addClass("active")}else if(j>=-182&&j<-114){$("#landing-tech-emv-2").addClass("active");$("#landing-tech-emv-3").addClass("active")}else if(j>=-114&&j<-46){$("#landing-tech-nfc-1").addClass("active")}else if(j>=-46&&j<24){$("#landing-tech-nfc-1").addClass("active");$("#landing-tech-nfc-2").addClass("active")}else if(j>=24){$("#landing-tech-nfc-1").addClass("active");$("#landing-tech-nfc-2").addClass("active");$("#landing-tech-nfc-3").addClass("active")}if(j>=i/-2&&j<0){c=true;$("#landing-payments > div > div").removeClass("active");

$("#landing-payments-1").addClass("active");l=j/(i/-1);

if(l<.9){$("#landing-payments-2").addClass("active")}if(l<.7){$("#landing-payments-6").addClass("active")}if(l<.6){$("#landing-payments-5").addClass("active")}if(l<.5){$("#landing-payments-3").addClass("active")}if(l<.3){$("#landing-payments-4").addClass("active")}if(l<.3){$("#landing-payments-7").addClass("active")}if(l<.3){$("#landing-payments-8").addClass("active");


setTimeout(function(){$("#landing-1").addClass("active")},200)}}else if(j>=0){c=true;$("#landing-payments > div > div").addClass("active");setTimeout(function(){$("#landing-1").addClass("active")},200)}else if(j<-1*i/2&&c){c=false;$("#landing-payments > div > div").removeClass("active")}j=$("#landing-2").offset().top-h;if(j>=0&&j<i/2){d=true;$("#landing-security > div").removeClass("active");

$("#landing-security-1").addClass("active");

l=j/(i/2);

if(l<.7){$("#landing-security-2").addClass("active")}if(l<.5){$("#landing-security-3").addClass("active");

setTimeout(function(){$("#landing-2").addClass("active")},200)}if(l<.4){$("#landing-security-4").addClass("active")}}else if(j<0){d=true;$("#landing-security > div").addClass("active");


setTimeout(function(){$("#landing-2").addClass("active")},200)}else if(j>=i/2&&d){d=false;$("#landing-security > div")

.removeClass("active")} 

j=h-$("#landing-3").offset().top;if(-2*j<i){setTimeout(function(){$("#landing-integrate-container1").addClass("active")},200)}
/*
if(j+i>=810&&h+i-$("#landing-4").offset().top<=50){e=true;k=j+i-810;$("#landing-3, #landing-3-reflection").css("background-position","100% "+k+"px");$("#landing-platform").css("top",188+k+"px")}else if(j+i<810&&e){e=false;$("#landing-3, #landing-3-reflection").css("background-position","100% 0px");$("#landing-platform").css("top","188px")}else if(h+i-$("#landing-4").offset().top>50)
*/
{e=true;k=$("#landing-3").height()-565;$("#landing-3, #landing-3-reflection").css("background-position","100% "+k+"px");$("#landing-platform").css("top",188+k+"px")}j=$("#landing-platform-header").offset().top-h;



if(j>=0&&j<i/2){f=true;$("#landing-register").addClass("active");$("#landing-platform-1").addClass("active");$("#landing-platformimg.toggle").removeClass("active");$("#landing-platform-container1").addClass("active");l=j/(i/2);if(l<.8){$("#landing-platform-2").addClass("active")}if(l<.6){$("#landing-platform-3").addClass("active")}}else if(j<0){f=true;$("#landing-register").addClass("active");$("#landing-platform-1").addClass("active");$("#landing-platform > img.toggle").addClass("active");$("#landing-platform-container1").addClass("active")}else if(j>=i/2){if(f){f=false;$("#landing-platform-1").removeClass("active");$("#landing-platform > img.toggle").removeClass("active")}if(j<5*i/6){$("#landing-register").addClass("active")}else{$("#landing-register").removeClass("active")}}j=$("#landing-4").offset().top-h;if(j<i/4){setTimeout(function(){$("#landing-4").addClass("active")},200)}g=setTimeout(function(){$("body").removeClass("disable-hover")},250)};$(window).on("scroll",h);var i=function(){$("#landing-header").css("height",$(window).height());h()};$(window).on("resize",i);var j=function(){if(a){return}a=true;$("#content").addClass("active");i();setTimeout(function(){if(!b){$("#landing-header-logo").addClass("active")}},900);setTimeout(function(){$("#landing-header > div > h1").addClass("active");$("#landing-header-logo").removeClass("active")},2e3);setTimeout(function(){$("#landing-header-preorder").addClass("active")},3500);setTimeout(function(){$("#landing-header-caret > div").addClass("active")},4e3);$("#landing-video > iframe").prop("src","https://player.vimeo.com/video/110337109?api=1&autoplay=0&badge=0&byline=0&loop=0&portrait=0&title=0")};$("#landing-header > div > img").load(j).each(function(){if(this.complete){j()}});setTimeout(j,1e3);i();$("#landing-header-caret").click(function(){$("html,body").animate({scrollTop:$(window).height()-80},1e3)});var k=$f($("#landing-video > iframe")[0]);var l=false;$(".video-button").click(function(){if(typeof ga!=="undefined"&&ga){ga("send","event","video-play","click")}$("#landing-video").css("visibility","visible");$("#landing-video").addClass("active");setTimeout(function(){k.api("play");l=true},400)});var m=function(){$("html,body").css("overflow","auto");$("#landing-video").removeClass("active");setTimeout(function(){$("#landing-video").css("visibility","hidden")},400);l=false};$(document).keyup(function(a){if(a.keyCode===27&&l){m();k.api("pause")}});k.addEvent("ready",function(){k.addEvent("finish",m)});$("#landing-video").click(function(){m();k.api("pause")});$("#landing-video > iframe").click(function(a){a.stopPropagation()})})();